package com.hatshop.server.models


import javax.persistence.*
import javax.validation.constraints.NotEmpty
import javax.validation.constraints.NotNull

// Generated Jun 19, 2015 2:01:18 AM by Hibernate Tools 4.3.1

/**
 * Audit generated by hbm2java
 */
@Entity
class Audit {
  @Id
  @GeneratedValue
  Integer id

  @NotNull
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(nullable = false)
  EOrder orders

  @NotNull
  @Temporal(TemporalType.TIMESTAMP)
  @Column(nullable = false, length = 29)
  Date createdOn

  @NotEmpty
  @Column(nullable = false)
  String message

  @NotNull
  @Column(nullable = false)
  Integer messageNumber

  Audit() {}

  Audit(EOrder orders, Date createdOn, String message, Integer messageNumber) {
    this.orders = orders
    this.createdOn = createdOn
    this.message = message
    this.messageNumber = messageNumber
  }
}


