package com.hatshop.server.models


import javax.persistence.*
import javax.validation.constraints.NotEmpty

// Generated Jun 19, 2015 2:01:18 AM by Hibernate Tools 4.3.1
/**
 * Category generated by hbm2java
 */
@Entity
class Category {
  Category() {}

  Category(Department department, String name, String description) {
    this.department = department
    this.name = name
    this.description = description
  }
  @Id
  @GeneratedValue
  Integer id

  @ManyToOne(fetch = FetchType.LAZY)
  Department department

  @NotEmpty
  @Column(nullable = false, length = 50)
  String name

  @Column(length = 1000)
  String description

  @ManyToMany
  @JoinTable(name = 'product_category',
    joinColumns = [@JoinColumn(name = "category_id", nullable = false, updatable = false)],
    inverseJoinColumns = [@JoinColumn(name = "product_id", nullable = false, updatable = false)])
  Set<Product> products = new HashSet<Product>(0)
}


