package com.hatshop.server.models
// Generated Jun 19, 2015 2:01:18 AM by Hibernate Tools 4.3.1


import javax.persistence.*
import javax.validation.constraints.Size

/**
 * OrderDetail generated by hbm2java
 */
@Entity
class OrderDetail implements Serializable {
  @EmbeddedId
  @AttributeOverrides([
    @AttributeOverride(name = "orderId", column = @Column(name = "order_id", nullable = false)),
    @AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false))])
  OrderDetailId id

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(nullable = false, insertable = false, updatable = false)
  EOrder orders

  @Size(max = 50)
  @Column(nullable = false, length = 50)
  String productName

  @Column(nullable = false)
  int quantity

  @Column(nullable = false, precision = 10)
  BigDecimal unitCost
}


