package com.hatshop.server.models
// Generated Jun 19, 2015 2:01:18 AM by Hibernate Tools 4.3.1


import javax.persistence.Column
import javax.persistence.Embeddable

/**
 * OrderDetailId generated by hbm2java
 */
@Embeddable
class OrderDetailId implements Serializable {
  @Column(nullable = false)
  int orderId

  @Column(nullable = false)
  int productId

  boolean equals(Object other) {
    if ((this == other)) return true
    if ((other == null)) return false
    if (!(other instanceof OrderDetailId)) return false
    OrderDetailId castOther = (OrderDetailId) other

    return (orderId == castOther.orderId) && (this.productId == castOther.productId)
  }

  int hashCode() {
    int result = 17

    result = 37 * result + this.getOrderId()
    result = 37 * result + this.getProductId()
    return result
  }
}


