package com.hatshop.server.models

import javax.persistence.*

// Generated Jun 19, 2015 2:01:18 AM by Hibernate Tools 4.3.1
/**
 * Review generated by hbm2java
 */
@Entity
@Table(name = "review", schema = "public")
class Review implements Serializable {
    @Id
    @Column(name = "id", unique = true, nullable = false)
    int id

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "customer_id", nullable = false)
    Customer customer

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false)
    Product product

    @Column(name = "review", nullable = false)
    String review

    @Column(name = "rating", nullable = false)
    short rating

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_on", nullable = false, length = 29)
    Date createdOn
}


