package com.hatshop.server.models

import javax.persistence.*
import javax.validation.constraints.NotEmpty

// Generated Jun 19, 2015 2:01:18 AM by Hibernate Tools 4.3.1

/**
 * ShippingRegion generated by hbm2java
 */
@Entity
class ShippingRegion implements Serializable {

  ShippingRegion() {}

  ShippingRegion(String shippingRegion) {
    this.shippingRegion = shippingRegion
  }
  @Id
  @GeneratedValue
  Integer id

  @NotEmpty
  @Column(nullable = false, length = 100)
  String shippingRegion

  @OneToMany(mappedBy = "shippingRegion")
  Set<Shipping> shippings = new HashSet<Shipping>(0)

  @OneToMany(mappedBy = "shippingRegion")
  Set<Customer> customers = new HashSet<Customer>(0)
}


