package com.hatshop.server.models
// Generated Jun 19, 2015 2:01:18 AM by Hibernate Tools 4.3.1


import javax.persistence.*

/**
 * Shipping generated by hbm2java
 */
@Entity
class Shipping implements Serializable {
    @Id
    @GeneratedValue
    int id
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(nullable = false)
    ShippingRegion shippingRegion

    @Column(nullable = false, length = 100)
    String shippingType

    @Column(nullable = false, precision = 10)
    BigDecimal shippingCost

    @OneToMany(mappedBy = "shipping")
    Set<EOrder> orders = new HashSet<EOrder>(0)

    Shipping() {}

    Shipping(String shippingType, BigDecimal shippingCost, ShippingRegion shippingRegion) {
        this.shippingRegion = shippingRegion
        this.shippingType = shippingType
        this.shippingCost = shippingCost
    }

    Shipping(String shippingType, BigDecimal shippingCost, ShippingRegion shippingRegion, Set<EOrder> orders) {
        this.shippingRegion = shippingRegion
        this.shippingType = shippingType
        this.shippingCost = shippingCost
        this.orders = orders
    }
}


