package com.hatshop.server.models

import com.fasterxml.jackson.annotation.JsonIdentityInfo
import com.fasterxml.jackson.annotation.ObjectIdGenerators
// Generated Jun 19, 2015 2:01:18 AM by Hibernate Tools 4.3.1


import javax.persistence.*

/**
 * ShippingRegion generated by hbm2java
 */
@Entity
@Table(name = "shipping_region", schema = "public")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id", scope = ShippingRegion.class)
class ShippingRegion implements Serializable {
    @Id
    @Column(name = "id", unique = true, nullable = false)
    int id

    @Column(name = "shipping_region", nullable = false, length = 100)
    String shippingRegion

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "shippingRegion")
    Set<Shipping> shippings = new HashSet<Shipping>(0)

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "shippingRegion")
    Set<Customer> customers = new HashSet<Customer>(0)

    ShippingRegion() {}

    ShippingRegion(int id, String shippingRegion) {
        this.id = id
        this.shippingRegion = shippingRegion
    }

    ShippingRegion(int id, String shippingRegion, Set<Shipping> shippings, Set<Customer> customers) {
        this.id = id
        this.shippingRegion = shippingRegion
        this.shippings = shippings
        this.customers = customers
    }
}


