package com.hatshop.server.models
// Generated Jun 19, 2015 2:01:18 AM by Hibernate Tools 4.3.1


import javax.persistence.*
import javax.validation.constraints.NotEmpty
import javax.validation.constraints.NotNull
import javax.validation.constraints.Size

/**
 * Shipping generated by hbm2java
 */
@Entity
class Shipping implements Serializable {
  @Id
  @GeneratedValue
  Integer id

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(nullable = false)
  ShippingRegion shippingRegion

  @NotEmpty
  @Size(max = 100)
  @Column(nullable = false, length = 100)
  String shippingType

  @NotNull
  @Column(nullable = false, precision = 10)
  BigDecimal shippingCost

  @OneToMany(mappedBy = "shipping")
  Set<EOrder> orders = new HashSet<EOrder>(0)

  Shipping() {}

  Shipping(String shippingType, BigDecimal shippingCost, ShippingRegion shippingRegion) {
    this.shippingRegion = shippingRegion
    this.shippingType = shippingType
    this.shippingCost = shippingCost
  }
}


