package com.hatshop.server.models

import javax.persistence.*

// Generated Jun 19, 2015 2:01:18 AM by Hibernate Tools 4.3.1

import javax.validation.constraints.NotEmpty

/**
 * ShippingRegion generated by hbm2java
 */
@Entity
class ShippingRegion implements Serializable {

    ShippingRegion() {}

    ShippingRegion(String shippingRegion) {
        this.shippingRegion = shippingRegion
    }

    ShippingRegion(String shippingRegion, Set<Shipping> shippings, Set<Customer> customers) {
        this.shippingRegion = shippingRegion
        this.shippings = shippings
        this.customers = customers
    }

    @Id
    @GeneratedValue
    int id

    @NotEmpty
    @Column(nullable = false, length = 100)
    String shippingRegion

    @OneToMany(mappedBy = "shippingRegion")
    Set<Shipping> shippings = new HashSet<Shipping>(0)

    @OneToMany(mappedBy = "shippingRegion")
    Set<Customer> customers = new HashSet<Customer>(0)
}


