package com.hatshop.server.models
// Generated Jun 19, 2015 2:01:18 AM by Hibernate Tools 4.3.1


import javax.persistence.Column
import javax.persistence.Embeddable

/**
 * ShoppingCartId generated by hbm2java
 */
@Embeddable
class ShoppingCartId implements Serializable {
    @Column(nullable = false, length = 32)
    String id

    @Column(nullable = false)
    int productId

    ShoppingCartId() {}

    ShoppingCartId(String id, int productId) {
        this.id = id
        this.productId = productId
    }

    boolean equals(Object other) {
        if ((this == other)) return true
        if ((other == null)) return false
        if (!(other instanceof ShoppingCartId)) return false
        ShoppingCartId castOther = (ShoppingCartId) other
        
        return ((this.id == castOther.id) || (this.id != null && castOther.id != null && this.id == castOther.id)) \
                && (productId == castOther.productId)
    }

    int hashCode() {
        int result = 17

        result = 37 * result + (id?.hashCode() ?: 0)
        result = 37 * result + productId
        return result
    }
}


