package com.hatshop.server.models

import javax.persistence.*
import javax.validation.constraints.NotNull

// Generated Jun 19, 2015 2:01:18 AM by Hibernate Tools 4.3.1
/**
 * ShoppingCart generated by hbm2java
 */
@Entity
class ShoppingCart implements Serializable {
  @EmbeddedId
  @AttributeOverrides([
    @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false, length = 32)),
    @AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false))])
  ShoppingCartId id

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(nullable = false, insertable = false, updatable = false)
  Product product

  @NotNull
  @Column(nullable = false)
  Integer quantity

  @NotNull
  @Column(nullable = false)
  Boolean buyNow

  @NotNull
  @Temporal(TemporalType.TIMESTAMP)
  @Column(nullable = false, length = 29)
  Date addedOn
}


