package com.hatshop.server.models
// Generated Jun 19, 2015 2:01:18 AM by Hibernate Tools 4.3.1


import javax.persistence.*

/**
 * Tax generated by hbm2java
 */
@Entity
class Tax implements Serializable {
    Tax() {}

    Tax(String taxType, BigDecimal taxPercentage) {
        this.taxType = taxType
        this.taxPercentage = taxPercentage
    }

    @Id
    @GeneratedValue
    int id

    @Column(nullable = false, length = 100)
    String taxType

    @Column(nullable = false, precision = 10)
    BigDecimal taxPercentage

    @OneToMany(mappedBy = "tax")
    Set<EOrder> orders = new HashSet<EOrder>(0)
}


