version: '3'

services:
  server:
    image: hatshop-server:latest
    ports:
      - "8080:8080"

  postgres:
    image: postgres:16.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: S3cr3tPa55w0rd

  client:
#    build: client
    image: hatshop-client:latest
    depends_on:
      server:
        condition: service_started
    ports:
      - "80:80"
