package com.hatshop.models
// Generated Jun 19, 2015 2:01:18 AM by Hibernate Tools 4.3.1


import javax.persistence.*

/**
 * Audit generated by hbm2java
 */
@Entity
@Table(name = "audit", schema = "public")
class Audit implements java.io.Serializable {
    @Id
    @Column(name = "id", unique = true, nullable = false)
    int id

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "order_id", nullable = false)
    EOrder orders

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_on", nullable = false, length = 29)
    Date createdOn

    @Column(name = "message", nullable = false)
    String message

    @Column(name = "message_number", nullable = false)
    int messageNumber

    Audit(){}

    Audit(int id, EOrder orders, Date createdOn, String message, int messageNumber) {
        this.id = id
        this.orders = orders
        this.createdOn = createdOn
        this.message = message
        this.messageNumber = messageNumber
    }
}


