spring:
  jpa:
    show-sql: true
  data:
    rest:
      base-path: api/hal
#      detection-strategy: annotated
  datasource:
    url: jdbc:h2:mem:test

logging.level:
  org.springframework.security.web.csrf: debug
