package com.hatshop_api.models

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.FetchType
import jakarta.persistence.GeneratedValue
import jakarta.persistence.Id
import jakarta.persistence.JoinColumn
import jakarta.persistence.ManyToOne
import jakarta.persistence.Temporal
import jakarta.persistence.TemporalType
import jakarta.validation.constraints.NotEmpty
import jakarta.validation.constraints.NotNull
import java.util.Date

/**
 * Audit generated by hbm2java
 */
@Entity
data class Audit(
  @Id
  @GeneratedValue
  var id: Int,

  @NotNull
  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(nullable = false)
  var orders: EOrder,

  @NotNull
  @Temporal(TemporalType.TIMESTAMP)
  @Column(nullable = false, length = 29)
  var createdOn: Date,

  @NotEmpty
  @Column(nullable = false)
  var message: String,

  @NotNull
  @Column(nullable = false)
  var messageNumber: Int,
)

